INSERT INTO truths (type, question) VALUES ('Truth', 'What was the most embarrassing thing you''ve ever done on a date?');
INSERT INTO truths (type, question) VALUES ('Truth', 'What is one thing you would do if you knew there no consequences?');
INSERT INTO truths (type, question) VALUES ('Truth', 'Who is the oldest person you have dated?');
INSERT INTO truths (type, question) VALUES ('Truth', 'How many times a week do you wear the same pants?');
INSERT INTO truths (type, question) VALUES ('Truth', 'What is one movie you are embarrassed to admit you enjoy?');
INSERT INTO truths (type, question) VALUES ('Truth', 'What is the strangest rumour you have heard about yourself?');
INSERT INTO truths (type, question) VALUES ('Truth', 'Who was your worst kiss ever?');
INSERT INTO truths (type, question) VALUES ('Truth', 'Have you ever told someone you wouldn not be home just so they wouldn not come over to yours?');
INSERT INTO truths (type, question) VALUES ('Truth', 'Who is your favourite family member?');
INSERT INTO truths (type, question) VALUES ('Truth', 'Tell us your most embarrassing vomit story.');
INSERT INTO truths (type, question) VALUES ('Truth', 'Tell us your cheesiest pick-up line.');
INSERT INTO truths (type, question) VALUES ('Truth', 'If you could get away with crime for a day, what crime would you commit and why?');
INSERT INTO truths (type, question) VALUES ('Truth', 'Has anyone ever accidentally seen you naked?');
INSERT INTO truths (type, question) VALUES ('Truth', 'Have you ever slept with someone then immediately regretted it?');
INSERT INTO truths (type, question) VALUES ('Truth', 'What is the scariest thing you have ever done?');
INSERT INTO truths (type, question) VALUES ('Truth', 'What is your biggest regret?');
INSERT INTO truths (type, question) VALUES ('Truth', 'What is a bad habit you have?');
INSERT INTO truths (type, question) VALUES ('Truth', 'What is one thing on your bucket list?');
INSERT INTO truths (type, question) VALUES ('Truth', 'When was the last time you cried?');
INSERT INTO truths (type, question) VALUES ('Truth', 'What is your guilty pleasure?');
INSERT INTO truths (type, question) VALUES ('Truth', 'Have you ever cheated on someone?');
INSERT INTO truths (type, question) VALUES ('Truth', 'What is your biggest fear?');
INSERT INTO truths (type, question) VALUES ('Truth', 'What is your biggest insecurity?');
INSERT INTO truths (type, question) VALUES ('Truth', 'What is something that no one else knows about you?');
INSERT INTO truths (type, question) VALUES ('Truth', 'What is one useless skill you would love to learn anyway?');
INSERT INTO truths (type, question) VALUES ('Truth', 'What is the most annoying thing about you?');
INSERT INTO truths (type, question) VALUES ('Truth', 'Describe the weirdest thing you have ever done while inebriated.');
INSERT INTO truths (type, question) VALUES ('Truth', 'Would you break up with your partner for $1 million?');
INSERT INTO truths (type, question) VALUES ('Truth', 'Have you ever had a crush on a coworker?');
INSERT INTO truths (type, question) VALUES ('Truth', 'What is one job you could never do?');
INSERT INTO truths (type, question) VALUES ('Truth', 'Have you ever ghosted a friend?');
INSERT INTO truths (type, question) VALUES ('Truth', 'If you switched genders for a day, what would you do?');
INSERT INTO truths (type, question) VALUES ('Truth', 'How many photo editing apps do you have on your phone?');
INSERT INTO truths (type, question) VALUES ('Truth', 'What is the most childish thing you still do?');
INSERT INTO truths (type, question) VALUES ('Truth', 'Have you ever lied for a friend?');
INSERT INTO truths (type, question) VALUES ('Truth', 'If you could become invisible, what is the worst thing you would do?');
INSERT INTO truths (type, question) VALUES ('Truth', 'What is one thing in your life you wish you could change?');
INSERT INTO truths (type, question) VALUES ('Truth', 'What was the greatest day of your life?');
INSERT INTO truths (type, question) VALUES ('Truth', 'What is your most absurd dealbreaker?');
INSERT INTO truths (type, question) VALUES ('Truth', 'How often do you wash your sheets?');
INSERT INTO truths (type, question) VALUES ('Truth', 'What is the last purchase you regretted?');
INSERT INTO truths (type, question) VALUES ('Truth', 'Have you ever had a one-night stand?');
INSERT INTO truths (type, question) VALUES ('Truth', 'What''s the last lie you told?');
INSERT INTO truths (type, question) VALUES ('Truth', 'Have you ever accidentally hit something (or someone!) with your car?');
INSERT INTO truths (type, question) VALUES ('Truth', 'If you met a genie, what would your three wishes be?');
INSERT INTO truths (type, question) VALUES ('Truth', 'What''s been your most physically painful experience?');
INSERT INTO truths (type, question) VALUES ('Truth', 'Who are you most jealous of?');
INSERT INTO truths (type, question) VALUES ('Truth', 'Have you ever lied to get out of a bad date? If so, what was the lie?');
INSERT INTO truths (type, question) VALUES ('Truth', 'If you farted in the elevator, would you blame someone else or say excuse me?');
INSERT INTO truths (type, question) VALUES ('Truth', 'Have you ever stolen something?');
INSERT INTO truths (type, question) VALUES ('Truth', 'What is your biggest pet peeve?');
INSERT INTO truths (type, question) VALUES ('Truth', 'Have you ever been caught gossiping about someone?');
INSERT INTO truths (type, question) VALUES ('Truth', 'What is the worst gift you have ever received?');
INSERT INTO truths (type, question) VALUES ('Truth', 'Do you have any irrational fears?');
INSERT INTO truths (type, question) VALUES ('Truth', 'What is the most embarrassing nickname you have ever had?');
INSERT INTO truths (type, question) VALUES ('Truth', 'Have you ever had a wardrobe malfunction in public?');
INSERT INTO truths (type, question) VALUES ('Truth', 'What is the dumbest way you have injured yourself?');
INSERT INTO truths (type, question) VALUES ('Truth', 'Have you ever lied about your age?');
INSERT INTO truths (type, question) VALUES ('Truth', 'What is the most unusual thing you find attractive in a person?');
INSERT INTO truths (type, question) VALUES ('Truth', 'What is the most embarrassing song on your playlist?');
INSERT INTO truths (type, question) VALUES ('Truth', 'Have you ever pretended to like a gift you did not actually like?');
INSERT INTO truths (type, question) VALUES ('Truth', 'What is the most embarrassing thing you have posted on social media?');
INSERT INTO truths (type, question) VALUES ('Truth', 'Have you ever been caught picking your nose?');
INSERT INTO truths (type, question) VALUES ('Truth', 'What is the most embarrassing thing you have done in front of a crush?');
INSERT INTO truths (type, question) VALUES ('Truth', 'Have you ever had a crush on a teacher?');
INSERT INTO truths (type, question) VALUES ('Truth', 'What is the most embarrassing thing your parents have caught you doing?');
INSERT INTO truths (type, question) VALUES ('Truth', 'Have you ever pretended to be sick to get out of something?');
INSERT INTO truths (type, question) VALUES ('Truth', 'What is the most embarrassing fashion trend you have participated in?');
INSERT INTO truths (type, question) VALUES ('Truth', 'Have you ever lied about your job to impress someone?');
INSERT INTO truths (type, question) VALUES ('Truth', 'What is the most embarrassing thing you have done at work?');
INSERT INTO truths (type, question) VALUES ('Truth', 'Have you ever accidentally sent a text to the wrong person?');
INSERT INTO truths (type, question) VALUES ('Truth', 'What is the most embarrassing thing that has happened to you in a public restroom?');
INSERT INTO truths (type, question) VALUES ('Truth', 'Have you ever been caught singing or dancing when you thought you were alone?');
INSERT INTO truths (type, question) VALUES ('Truth', 'What is the most embarrassing nickname someone has given you?');
INSERT INTO truths (type, question) VALUES ('Truth', 'Have you ever tripped or fallen in public?');
INSERT INTO truths (type, question) VALUES ('Truth', 'What is the most embarrassing thing you have said in a job interview?');
INSERT INTO truths (type, question) VALUES ('Truth', 'Have you ever been caught talking to yourself?');
INSERT INTO truths (type, question) VALUES ('Truth', 'What is the most embarrassing thing you have done at a party?');
INSERT INTO truths (type, question) VALUES ('Truth', 'Have you ever had food stuck in your teeth without realizing it?');
INSERT INTO truths (type, question) VALUES ('Truth', 'What is the most embarrassing thing you have done while drunk?');
INSERT INTO truths (type, question) VALUES ('Truth', 'Have you ever accidentally sent a love letter to the wrong person?');
INSERT INTO truths (type, question) VALUES ('Truth', 'What is the most embarrassing thing you have done while sleepwalking?');
INSERT INTO truths (type, question) VALUES ('Truth', 'Have you ever had a wardrobe malfunction on stage or in front of an audience?');
INSERT INTO truths (type, question) VALUES ('Truth', 'What is the most embarrassing thing you have done in a job setting?');
INSERT INTO truths (type, question) VALUES ('Truth', 'Have you ever been caught talking to yourself in public?');
INSERT INTO truths (type, question) VALUES ('Truth', 'What is the most embarrassing text message you have sent to the wrong person?');
INSERT INTO truths (type, question) VALUES ('Truth', 'Have you ever had an awkward encounter with a celebrity?');
INSERT INTO truths (type, question) VALUES ('Truth', 'Have you ever had a wardrobe malfunction while exercising or playing sports?');
INSERT INTO truths (type, question) VALUES ('Truth', 'What is the most embarrassing thing you have done in a classroom or lecture hall?');
INSERT INTO truths (type, question) VALUES ('Truth', 'Have you ever been caught snooping through someone else''s belongings?');
INSERT INTO truths (type, question) VALUES ('Truth', 'What is the most embarrassing thing you have done on a video call?');
INSERT INTO truths (type, question) VALUES ('Truth', 'Have you ever accidentally called someone by the wrong name?');
INSERT INTO truths (type, question) VALUES ('Truth', 'What is the most embarrassing thing you have done in a public speaking situation?');
INSERT INTO truths (type, question) VALUES ('Truth', 'What is your all-time favorite video game and why?');
INSERT INTO truths (type, question) VALUES ('Truth', 'Have you ever played a horror game that was too scary to finish?');
INSERT INTO truths (type, question) VALUES ('Truth', 'What is the scariest video game moment you have experienced?');
INSERT INTO truths (type, question) VALUES ('Truth', 'Have you ever screamed or shouted while playing a video game?');
INSERT INTO truths (type, question) VALUES ('Truth', 'What is your favorite horror video game and why?');
INSERT INTO truths (type, question) VALUES ('Truth', 'Have you ever streamed a horror game and regretted it afterwards?');
INSERT INTO truths (type, question) VALUES ('Truth', 'What is the most embarrassing moment you''ve had while streaming on Twitch?');
INSERT INTO truths (type, question) VALUES ('Truth', 'Have you ever received hate or negative comments while streaming? How did you handle it?');
INSERT INTO truths (type, question) VALUES ('Truth', 'What is the scariest jump scare you''ve encountered in a video game?');
INSERT INTO truths (type, question) VALUES ('Truth', 'Have you ever broken a controller or keyboard out of frustration while gaming?');
INSERT INTO truths (type, question) VALUES ('Truth', 'What is your favorite video game genre to stream on Twitch?');
INSERT INTO truths (type, question) VALUES ('Truth', 'Have you ever played a video game for an entire day without taking a break?');
INSERT INTO truths (type, question) VALUES ('Truth', 'What is the funniest glitch or bug you''ve encountered while playing a video game?');
INSERT INTO truths (type, question) VALUES ('Truth', 'Have you ever cried while playing a video game? If so, which game and why?');
INSERT INTO truths (type, question) VALUES ('Truth', 'What is your favorite Twitch emote and why?');
INSERT INTO truths (type, question) VALUES ('Truth', 'Have you ever rage quit a video game? What caused it?');
INSERT INTO truths (type, question) VALUES ('Truth', 'What is the most challenging video game you''ve ever played?');
INSERT INTO truths (type, question) VALUES ('Truth', 'Have you ever used cheats or hacks in a multiplayer game?');
INSERT INTO truths (type, question) VALUES ('Truth', 'What is the longest consecutive hours you''ve streamed on Twitch?');
INSERT INTO truths (type, question) VALUES ('Truth', 'Have you ever encountered a toxic player while gaming? How did you handle it?');
INSERT INTO truths (type, question) VALUES ('Truth', 'What is the most memorable Twitch raid or host you''ve received?');
INSERT INTO truths (type, question) VALUES ('Truth', 'Have you ever played a horror game alone in the dark?');
INSERT INTO truths (type, question) VALUES ('Truth', 'What is the funniest moment you''ve had while streaming a video game?');
INSERT INTO truths (type, question) VALUES ('Truth', 'Have you ever dressed up as a video game character for a stream?');
INSERT INTO truths (type, question) VALUES ('Truth', 'What is your most embarrassing defeat in a multiplayer game?');
INSERT INTO truths (type, question) VALUES ('Truth', 'Have you ever encountered a ghost or paranormal activity while streaming?');
INSERT INTO truths (type, question) VALUES ('Truth', 'What is the most frustrating puzzle or level you''ve encountered in a video game?');
INSERT INTO truths (type, question) VALUES ('Truth', 'Have you ever had a game crash or freeze during an important moment?');
INSERT INTO truths (type, question) VALUES ('Truth', 'What is your favorite Twitch streamer and why?');
INSERT INTO truths (type, question) VALUES ('Truth', 'Have you ever played a video game that made you feel genuinely scared or anxious?');
INSERT INTO truths (type, question) VALUES ('Truth', 'What is the most memorable boss battle you''ve experienced in a video game?');
INSERT INTO truths (type, question) VALUES ('Truth', 'Have you ever played a video game that made you cry or feel emotional?');
INSERT INTO truths (type, question) VALUES ('Truth', 'What is the funniest or most entertaining Twitch chat interaction you''ve had?');
INSERT INTO truths (type, question) VALUES ('Truth', 'Have you ever received a donation or gift from a viewer while streaming?');
INSERT INTO truths (type, question) VALUES ('Truth', 'What is the scariest moment you''ve encountered while playing a horror game?');
INSERT INTO truths (type, question) VALUES ('Truth', 'Have you ever played a video game that gave you nightmares?');
INSERT INTO truths (type, question) VALUES ('Truth', 'What is your favorite video game console of all time and why?');
INSERT INTO truths (type, question) VALUES ('Truth', 'Have you ever cosplayed as a video game character at a convention?');
INSERT INTO truths (type, question) VALUES ('Truth', 'What is the most challenging achievement or trophy you''ve unlocked in a game?');
INSERT INTO truths (type, question) VALUES ('Truth', 'Have you ever encountered a game-breaking bug or glitch that ruined your experience?');
INSERT INTO truths (type, question) VALUES ('Truth', 'What is your favorite horror movie that has inspired video games?');
INSERT INTO truths (type, question) VALUES ('Truth', 'Have you ever played a multiplayer game competitively? How did you perform?');
INSERT INTO truths (type, question) VALUES ('Truth', 'What is the most unexpected or surprising moment you''ve had while streaming?');
INSERT INTO truths (type, question) VALUES ('Truth', 'Have you ever been recognized or approached by a viewer in real life?');
INSERT INTO truths (type, question) VALUES ('Truth', 'What is your favorite video game merchandise or collectible that you own?');
INSERT INTO truths (type, question) VALUES ('Truth', 'Have you ever had to deal with internet trolls or harassment while streaming?');
INSERT INTO truths (type, question) VALUES ('Truth', 'What is the most memorable jump scare you''ve experienced in a horror game?');
INSERT INTO truths (type, question) VALUES ('Truth', 'Have you ever participated in a charity stream or gaming marathon?');
INSERT INTO truths (type, question) VALUES ('Truth', 'What is your favorite video game soundtrack of all time?');
INSERT INTO truths (type, question) VALUES ('Truth', 'Have you ever met or interacted with any famous gamers or Twitch streamers?');
INSERT INTO truths (type, question) VALUES ('Truth', 'What was your favorite game to play as a child?');
INSERT INTO truths (type, question) VALUES ('Truth', 'Did you have any imaginary friends or pretend playmates when you were younger?');
INSERT INTO truths (type, question) VALUES ('Truth', 'What was your favorite outdoor activity or game during your childhood?');
INSERT INTO truths (type, question) VALUES ('Truth', 'Did you have any special traditions or rituals with your family during holidays or special occasions when you were a child?');
INSERT INTO truths (type, question) VALUES ('Truth', 'What was the most memorable adventure or mischievous act you did as a child?');
INSERT INTO truths (type, question) VALUES ('Truth', 'Did you have any unique talents or hobbies that you pursued during your childhood?');
INSERT INTO truths (type, question) VALUES ('Truth', 'What was your favorite toy or stuffed animal that you cherished as a child?');

-- Dares
INSERT INTO dares (type, question) VALUES ('Dare', 'Eat a spoonful of hot sauce');
INSERT INTO dares (type, question) VALUES ('Dare', 'Sing a song in a public place');
INSERT INTO dares (type, question) VALUES ('Dare', 'Do a handstand for 30 seconds');
INSERT INTO dares (type, question) VALUES ('Dare', 'Eat a raw onion');
INSERT INTO dares (type, question) VALUES ('Dare', 'Dance like nobody is watching');
INSERT INTO dares (type, question) VALUES ('Dare', 'Give a stranger a compliment');
INSERT INTO dares (type, question) VALUES ('Dare', 'Walk on your hands for 10 steps');
INSERT INTO dares (type, question) VALUES ('Dare', 'Eat a spoonful of mustard');
INSERT INTO dares (type, question) VALUES ('Dare', 'Do 20 push-ups in a row');
INSERT INTO dares (type, question) VALUES ('Dare', 'Take a selfie with a random person');
INSERT INTO dares (type, question) VALUES ('Dare', 'Eat a spoonful of mayonnaise');
INSERT INTO dares (type, question) VALUES ('Dare', 'Do a cartwheel in a public place');
INSERT INTO dares (type, question) VALUES ('Dare', 'Do a funny dance in the middle of a crowd');
INSERT INTO dares (type, question) VALUES ('Dare', 'Eat a raw egg');
INSERT INTO dares (type, question) VALUES ('Dare', 'Give a high-five to a stranger');
INSERT INTO dares (type, question) VALUES ('Dare', 'Walk backwards for 50 steps');
INSERT INTO dares (type, question) VALUES ('Dare', 'Eat a spoonful of wasabi');
INSERT INTO dares (type, question) VALUES ('Dare', 'Do 10 jumping jacks in a row');
INSERT INTO dares (type, question) VALUES ('Dare', 'Take a photo with a statue');
INSERT INTO dares (type, question) VALUES ('Dare', 'Eat a spoonful of chili powder');
INSERT INTO dares (type, question) VALUES ('Dare', 'Do a one-minute plank');
INSERT INTO dares (type, question) VALUES ('Dare', 'Give a random person a hug');
INSERT INTO dares (type, question) VALUES ('Dare', 'Eat a spoonful of horseradish');
INSERT INTO dares (type, question) VALUES ('Dare', 'Do a silly walk down the street');
INSERT INTO dares (type, question) VALUES ('Dare', 'Eat a spoonful of peanut butter');
INSERT INTO dares (type, question) VALUES ('Dare', 'Imitate your favorite celebrity');
INSERT INTO dares (type, question) VALUES ('Dare', 'Do a 10-minute dance party on stream');
INSERT INTO dares (type, question) VALUES ('Dare', 'Attempt a world record on stream');
INSERT INTO dares (type, question) VALUES ('Dare', 'Do a blindfolded gaming session on stream');
INSERT INTO dares (type, question) VALUES ('Dare', 'Sing a song chosen by the chat on stream');
INSERT INTO dares (type, question) VALUES ('Dare', 'Wear a silly costume while streaming');
INSERT INTO dares (type, question) VALUES ('Dare', 'Do a freestyle rap about your viewers on stream');
INSERT INTO dares (type, question) VALUES ('Dare', 'Play a game using only voice commands on stream');
INSERT INTO dares (type, question) VALUES ('Dare', 'Eat a spicy chili pepper while streaming');
INSERT INTO dares (type, question) VALUES ('Dare', 'Give a shout-out to a random viewer on stream');
INSERT INTO dares (type, question) VALUES ('Dare', 'Perform a magic trick live on stream');
INSERT INTO dares (type, question) VALUES ('Dare', 'Attempt a difficult gaming challenge on stream');
INSERT INTO dares (type, question) VALUES ('Dare', 'Invite a guest streamer for a collaboration');
INSERT INTO dares (type, question) VALUES ('Dare', 'Do a live drawing session requested by the chat on stream');
INSERT INTO dares (type, question) VALUES ('Dare', 'Take a shot of hot sauce for every donation received on stream');
INSERT INTO dares (type, question) VALUES ('Dare', 'Complete a game using only your feet on stream');
INSERT INTO dares (type, question) VALUES ('Dare', 'Perform a cosplay of a character chosen by the chat on stream');
INSERT INTO dares (type, question) VALUES ('Dare', 'Attempt a speedrun of a game on stream');
INSERT INTO dares (type, question) VALUES ('Dare', 'Let the chat choose your next game to play on stream');
INSERT INTO dares (type, question) VALUES ('Dare', 'Eat a spoonful of cinnamon while streaming');
INSERT INTO dares (type, question) VALUES ('Dare', 'Do a karaoke session with chat-requested songs on stream');
INSERT INTO dares (type, question) VALUES ('Dare', 'Play a horror game in complete darkness on stream');
INSERT INTO dares (type, question) VALUES ('Dare', 'Attempt a no-hit run of a challenging game on stream');
INSERT INTO dares (type, question) VALUES ('Dare', 'Have a dance-off with a viewer on stream');
INSERT INTO dares (type, question) VALUES ('Dare', 'Create a piece of artwork based on viewer suggestions on stream');
INSERT INTO dares (type, question) VALUES ('Dare', 'Try gaming with inverted controls on stream');
INSERT INTO dares (type, question) VALUES ('Dare', 'Play a game blindfolded with chat as your guide on stream');
INSERT INTO dares (type, question) VALUES ('Dare', 'Do the chicken dance in a public place');
INSERT INTO dares (type, question) VALUES ('Dare', 'Wear your clothes inside out for the rest of the day');
INSERT INTO dares (type, question) VALUES ('Dare', 'Speak in a funny accent for the next hour');
INSERT INTO dares (type, question) VALUES ('Dare', 'Put on a funny hat and wear it all day');
INSERT INTO dares (type, question) VALUES ('Dare', 'Talk to an inanimate object like it iss your best friend');
INSERT INTO dares (type, question) VALUES ('Dare', 'Draw a silly face on your hand and talk to it during a conversation');
INSERT INTO dares (type, question) VALUES ('Dare', 'Sing a nursery rhyme in a loud voice in a crowded place');
INSERT INTO dares (type, question) VALUES ('Dare', 'Wear mismatched shoes for the next hour');
INSERT INTO dares (type, question) VALUES ('Dare', 'Do a funny dance every time someone says your name');
INSERT INTO dares (type, question) VALUES ('Dare', 'Talk to a random stranger and pretend you are long-lost friends');
INSERT INTO dares (type, question) VALUES ('Dare', 'Wear a fake mustache for the rest of the day');
INSERT INTO dares (type, question) VALUES ('Dare', 'Do a funny walk everywhere you go for the next hour');
INSERT INTO dares (type, question) VALUES ('Dare', 'Tell a joke to a stranger and make them laugh');
INSERT INTO dares (type, question) VALUES ('Dare', 'Wear your underwear on top of your pants for the next hour');
INSERT INTO dares (type, question) VALUES ('Dare', 'Make funny faces at yourself in a mirror for 5 minutes');
INSERT INTO dares (type, question) VALUES ('Dare', 'Do a dramatic reading of a cereal box');
INSERT INTO dares (type, question) VALUES ('Dare', 'Wear a sign that says "Free Hugs" and offer hugs to strangers');
INSERT INTO dares (type, question) VALUES ('Dare', 'Pretend to be a news reporter and interview random people on the street');
INSERT INTO dares (type, question) VALUES ('Dare', 'Talk in rhymes for the next 30 minutes');
INSERT INTO dares (type, question) VALUES ('Dare', 'Wear your clothes backward for the rest of the day');
INSERT INTO dares (type, question) VALUES ('Dare', 'Pretend to be a statue in a public place and see how long you can stay still');
INSERT INTO dares (type, question) VALUES ('Dare', 'Walk in slow motion wherever you go for the next hour');
INSERT INTO dares (type, question) VALUES ('Dare', 'Make a funny face and take a selfie with a stranger');
INSERT INTO dares (type, question) VALUES ('Dare', 'Wear a pair of underwear on your head for 10 minutes');
INSERT INTO dares (type, question) VALUES ('Dare', 'Try to lick your elbow in front of someone without any explanation');
INSERT INTO dares (type, question) VALUES ('Dare', 'Talk to your pet as if they can understand and respond to you');
INSERT INTO dares (type, question) VALUES ('Dare', 'Post a funny picture of yourself on social media');
INSERT INTO dares (type, question) VALUES ('Dare', 'Send a random friend request to someone you do not know on social media');
INSERT INTO dares (type, question) VALUES ('Dare', 'Share an embarrassing childhood photo on social media');
INSERT INTO dares (type, question) VALUES ('Dare', 'Comment on a celebrity''s social media post with a funny message');
INSERT INTO dares (type, question) VALUES ('Dare', 'Create a TikTok dance and share it on social media');
INSERT INTO dares (type, question) VALUES ('Dare', 'Post a funny video of yourself singing a silly song on social media');
INSERT INTO dares (type, question) VALUES ('Dare', 'Change your profile picture to a funny meme for 24 hours');
INSERT INTO dares (type, question) VALUES ('Dare', 'Write a funny poem or limerick and post it on social media');
INSERT INTO dares (type, question) VALUES ('Dare', 'Start a live stream on a social media platform and do something silly');
INSERT INTO dares (type, question) VALUES ('Dare', 'Make a funny parody account on a social media platform and post funny content');
INSERT INTO dares (type, question) VALUES ('Dare', 'Create a funny meme and share it on social media');
INSERT INTO dares (type, question) VALUES ('Dare', 'Send a funny DM to a random person on social media');
INSERT INTO dares (type, question) VALUES ('Dare', 'Post a funny caption on a friend''s social media post');
INSERT INTO dares (type, question) VALUES ('Dare', 'Create a poll on social media with a funny or unusual question');
INSERT INTO dares (type, question) VALUES ('Dare', 'Take a screenshot of your most embarrassing text conversation and post it on social media');
INSERT INTO dares (type, question) VALUES ('Dare', 'Write a funny review for a product or service on a social media platform');
INSERT INTO dares (type, question) VALUES ('Dare', 'Post a photo of yourself making a funny face on social media');
INSERT INTO dares (type, question) VALUES ('Dare', 'Share a hilarious joke or pun on social media');
INSERT INTO dares (type, question) VALUES ('Dare', 'Do a social media challenge and share the video or photos');
INSERT INTO dares (type, question) VALUES ('Dare', 'Share a funny and embarrassing story about yourself on social media');
INSERT INTO dares (type, question) VALUES ('Dare', 'Start a funny hashtag trend on social media and encourage others to participate');
INSERT INTO dares (type, question) VALUES ('Dare', 'Post a photo of yourself wearing a funny outfit on social media');
INSERT INTO dares (type, question) VALUES ('Dare', 'Create a funny comic strip and share it on social media');
INSERT INTO dares (type, question) VALUES ('Dare', 'Send a funny GIF to a random friend on social media');
INSERT INTO dares (type, question) VALUES ('Dare', 'Post a funny and exaggerated story about something that happened to you on social media');
INSERT INTO dares (type, question) VALUES ('Dare', 'Change your bio on a social media platform to a funny and creative description');
INSERT INTO dares (type, question) VALUES ('Dare', 'Do a handstand while drinking a glass of water');
INSERT INTO dares (type, question) VALUES ('Dare', 'Eat a spoonful of hot chili peppers');
INSERT INTO dares (type, question) VALUES ('Dare', 'Sing the national anthem in a funny voice');
INSERT INTO dares (type, question) VALUES ('Dare', 'Do 10 backflips in a row');
INSERT INTO dares (type, question) VALUES ('Dare', 'Eat a spoonful of soy sauce');
INSERT INTO dares (type, question) VALUES ('Dare', 'Imitate a famous movie character');
INSERT INTO dares (type, question) VALUES ('Dare', 'Do a breakdance routine');
INSERT INTO dares (type, question) VALUES ('Dare', 'Eat a spoonful of pickles');
INSERT INTO dares (type, question) VALUES ('Dare', 'Try to touch your nose with your tongue');
INSERT INTO dares (type, question) VALUES ('Dare', 'Balance a spoon on your nose for 1 minute');
INSERT INTO dares (type, question) VALUES ('Dare', 'Eat a spoonful of ketchup');
INSERT INTO dares (type, question) VALUES ('Dare', 'Do 20 burpees in a row');
INSERT INTO dares (type, question) VALUES ('Dare', 'Eat a whole lemon without making a face');
INSERT INTO dares (type, question) VALUES ('Dare', 'Mimic the sound of a monkey for 1 minute');
INSERT INTO dares (type, question) VALUES ('Dare', 'Do a handstand push-up against a wall');
INSERT INTO dares (type, question) VALUES ('Dare', 'Eat a spoonful of honey');
INSERT INTO dares (type, question) VALUES ('Dare', 'Speak in a British accent for the rest of the day');
INSERT INTO dares (type, question) VALUES ('Dare', 'Eat a spoonful of Nutella');
INSERT INTO dares (type, question) VALUES ('Dare', 'Do 10 somersaults in a row');
INSERT INTO dares (type, question) VALUES ('Dare', 'Eat a raw jalapeño pepper');
INSERT INTO dares (type, question) VALUES ('Dare', 'Imitate your favorite cartoon character');
INSERT INTO dares (type, question) VALUES ('Dare', 'Do a handstand walk for 10 steps');
INSERT INTO dares (type, question) VALUES ('Dare', 'Eat a spoonful of barbecue sauce');
INSERT INTO dares (type, question) VALUES ('Dare', 'Try to lick your elbow');
INSERT INTO dares (type, question) VALUES ('Dare', 'Do 10 tuck jumps in a row');
INSERT INTO dares (type, question) VALUES ('Dare', 'Eat a spoonful of salsa');
INSERT INTO dares (type, question) VALUES ('Dare', 'Yell out the first word that comes to your mind.')
INSERT INTO dares (type, question) VALUES ('Dare', 'Fake cry')
INSERT INTO dares (type, question) VALUES ('Dare', 'Hold your nose while you sing the chorus of your favorite song')
INSERT INTO dares (type, question) VALUES ('Dare', 'Fill your mouth with water, and each person in the group must tell the funniest joke they know. If you spit up the water, you have to eat a spoonful of dirt')
INSERT INTO dares (type, question) VALUES ('Dare', 'Only speak in rhymes for the rest of the game')
INSERT INTO dares (type, question) VALUES ('Dare', 'Do not say "I." for 30 minutes')
INSERT INTO dares (type, question) VALUES ('Dare', 'Make up a rap about koalas')
INSERT INTO dares (type, question) VALUES ('Dare', 'Silently do the macarena')
INSERT INTO dares (type, question) VALUES ('Dare', 'Sing the “I Love You” Barney song')
INSERT INTO dares (type, question) VALUES ('Dare', 'For the next 15 minutes, only speak in baby talk')
INSERT INTO dares (type, question) VALUES ('Dare', 'Tweet or update your Facebook status to "I think eggplants are sexy."')
INSERT INTO dares (type, question) VALUES ('Dare', 'One by one, make up a title for each player''s movie about their life.')
INSERT INTO dares (type, question) VALUES ('Dare', 'Tweet to “I am coming ... I am coming ... " Then, one minute later, change it to "I just came.')
INSERT INTO dares (type, question) VALUES ('Dare', 'Use a fake accent for the rest of the night.')
INSERT INTO dares (type, question) VALUES ('Dare', 'Do a moonwalk.')
INSERT INTO dares (type, question) VALUES ('Dare', 'Talk for a minute without using the letter “E.”')
INSERT INTO dares (type, question) VALUES ('Dare', 'Write a poem about a toilet')
INSERT INTO dares (type, question) VALUES ('Dare', 'Draw a picture of yourself as a superhero.')
INSERT INTO dares (type, question) VALUES ('Dare', 'Do a dramatic reading of a recipe.')
INSERT INTO dares (type, question) VALUES ('Dare', 'Tell a story using only three words at a time.')
INSERT INTO dares (type, question) VALUES ('Dare', 'Recite the alphabet backwards.')

-- Would you rathers
INSERT INTO wyrs (type, question) VALUES ('Would You Rather', 'Have the ability to time travel or have the ability to teleport?');
INSERT INTO wyrs (type, question) VALUES ('Would You Rather', 'Live in a world without books or live in a world without music?');
INSERT INTO wyrs (type, question) VALUES ('Would You Rather', 'Always have to wear a tiara or always have to wear a crown?');
INSERT INTO wyrs (type, question) VALUES ('Would You Rather', 'Be able to jump as high as a kangaroo or swim as fast as a dolphin?');
INSERT INTO wyrs (type, question) VALUES ('Would You Rather', 'Have a personal photographer or a personal chef?');
INSERT INTO wyrs (type, question) VALUES ('Would You Rather', 'Always have to wear a crown or always have to wear wings?');
INSERT INTO wyrs (type, question) VALUES ('Would You Rather', 'Be able to talk to plants or have the ability to heal any illness?');
INSERT INTO wyrs (type, question) VALUES ('Would You Rather', 'Have the ability to control the elements (fire, water, earth, air) or have the ability to shapeshift into any animal?');
INSERT INTO wyrs (type, question) VALUES ('Would You Rather', 'Always have to wear a tuxedo or a ball gown?');
INSERT INTO wyrs (type, question) VALUES ('Would You Rather', 'Be able to travel to the past or travel to the future?');
INSERT INTO wyrs (type, question) VALUES ('Would You Rather', 'Have a pet lion or a pet tiger?');
INSERT INTO wyrs (type, question) VALUES ('Would You Rather', 'Always have to wear a wizard''s robe or a fairy''s dress?');
INSERT INTO wyrs (type, question) VALUES ('Would You Rather', 'Be able to speak and understand all languages or have the ability to teleport?');
INSERT INTO wyrs (type, question) VALUES ('Would You Rather', 'Have the ability to control plants or have the ability to control the weather?');
INSERT INTO wyrs (type, question) VALUES ('Would You Rather', 'Always have to wear a cape or always have to wear a crown?');
INSERT INTO wyrs (type, question) VALUES ('Would You Rather', 'Be able to breathe fire or have super strength?');
INSERT INTO wyrs (type, question) VALUES ('Would You Rather', 'Have a personal assistant or a personal trainer?');
INSERT INTO wyrs (type, question) VALUES ('Would You Rather', 'Always have to wear a superhero costume or a fairy tale costume in public?');
INSERT INTO wyrs (type, question) VALUES ('Would You Rather', 'Be able to talk to animals or be able to speak any human language?');
INSERT INTO wyrs (type, question) VALUES ('Would You Rather', 'Have the ability to control gravity or have the ability to control time?');
INSERT INTO wyrs (type, question) VALUES ('Would You Rather', 'Be able to run as fast as a cheetah or fly like a bird?');
INSERT INTO wyrs (type, question) VALUES ('Would You Rather', 'Have a personal hairstylist or a personal makeup artist?');
INSERT INTO wyrs (type, question) VALUES ('Would You Rather', 'Always have to wear a cape or always have to wear a hat?');
INSERT INTO wyrs (type, question) VALUES ('Would You Rather', 'Be able to breathe underwater or have the ability to turn invisible?');
INSERT INTO wyrs (type, question) VALUES ('Would You Rather', 'Live in a castle or live in a spaceship?');
INSERT INTO wyrs (type, question) VALUES ('Would You Rather', 'Have the ability to speak with animals or be able to talk to the dead?');
INSERT INTO wyrs (type, question) VALUES ('Would You Rather', 'Always have to wear a bowtie or a bow in your hair?');
INSERT INTO wyrs (type, question) VALUES ('Would You Rather', 'Be able to jump as high as a kangaroo or walk on water?');
INSERT INTO wyrs (type, question) VALUES ('Would You Rather', 'Have a personal trainer or a personal chef?');
INSERT INTO wyrs (type, question) VALUES ('Would You Rather', 'Always have to wear a superhero costume or always have to wear a princess gown?');
INSERT INTO wyrs (type, question) VALUES ('Would You Rather', 'Be able to communicate with animals or be able to speak every language fluently?');
INSERT INTO wyrs (type, question) VALUES ('Would You Rather', 'Live in a treehouse or in an underwater city?');
INSERT INTO wyrs (type, question) VALUES ('Would You Rather', 'Have the ability to breathe underwater or have the ability to teleport?');
INSERT INTO wyrs (type, question) VALUES ('Would You Rather', 'Always have to wear a cape or always have to wear a mask?');
INSERT INTO wyrs (type, question) VALUES ('Would You Rather', 'Be able to control fire or control lightning?');
INSERT INTO wyrs (type, question) VALUES ('Would You Rather', 'Have a pet tiger or a pet elephant?');
INSERT INTO wyrs (type, question) VALUES ('Would You Rather', 'Always have to speak in riddles or in song lyrics?');
INSERT INTO wyrs (type, question) VALUES ('Would You Rather', 'Have the ability to freeze time or rewind time?');
INSERT INTO wyrs (type, question) VALUES ('Would You Rather', 'Be a famous actor/actress or a famous musician?');
INSERT INTO wyrs (type, question) VALUES ('Would You Rather', 'Always have to wear a top hat or always have to wear sunglasses?');
INSERT INTO wyrs (type, question) VALUES ('Would You Rather', 'Be able to turn into any animal at will or have the ability to speak and understand all human languages?');
INSERT INTO wyrs (type, question) VALUES ('Would You Rather', 'Have the ability to control time or have the ability to control gravity?');
INSERT INTO wyrs (type, question) VALUES ('Would You Rather', 'Be able to communicate with trees or be able to communicate with the ocean?');
INSERT INTO wyrs (type, question) VALUES ('Would You Rather', 'Have a personal makeup artist or a personal trainer?');
INSERT INTO wyrs (type, question) VALUES ('Would You Rather', 'Always have to wear a crown or always have to wear a magic wand?');
INSERT INTO wyrs (type, question) VALUES ('Would You Rather', 'Be able to fly like a bird or be able to breathe underwater?');
INSERT INTO wyrs (type, question) VALUES ('Would You Rather', 'Always have to speak in rhyme or always have to speak in riddles?');
INSERT INTO wyrs (type, question) VALUES ('Would You Rather', 'Have the ability to control time or have the ability to teleport?');
INSERT INTO wyrs (type, question) VALUES ('Would You Rather', 'Live in a world without technology or live in a world without nature?');
INSERT INTO wyrs (type, question) VALUES ('Would You Rather', 'Have a personal robot assistant or a personal flying car?');
INSERT INTO wyrs (type, question) VALUES ('Would You Rather', 'Always have to wear mismatched shoes or always have to wear mismatched socks?');
INSERT INTO wyrs (type, question) VALUES ('Would You Rather', 'Be able to speak with animals or be able to speak all foreign languages fluently?');
INSERT INTO wyrs (type, question) VALUES ('Would You Rather', 'Have the ability to control fire or have the ability to control water?');
INSERT INTO wyrs (type, question) VALUES ('Would You Rather', 'Always have to wear a clown costume or always have to wear a superhero costume?');
INSERT INTO wyrs (type, question) VALUES ('Would You Rather', 'Be able to read minds or be able to see the future?');
INSERT INTO wyrs (type, question) VALUES ('Would You Rather', 'Have a personal chef or a personal masseuse?');
INSERT INTO wyrs (type, question) VALUES ('Would You Rather', 'Always have to wear a hat or always have to wear sunglasses?');
INSERT INTO wyrs (type, question) VALUES ('Would You Rather', 'Be able to fly like a bird or be able to swim like a fish?');
INSERT INTO wyrs (type, question) VALUES ('Would You Rather', 'Live in a world without internet or live in a world without cell phones?');
INSERT INTO wyrs (type, question) VALUES ('Would You Rather', 'Have the ability to control fire or have the ability to control ice?');
INSERT INTO wyrs (type, question) VALUES ('Would You Rather', 'Always have to wear a clown wig or always have to wear a jester hat?');
INSERT INTO wyrs (type, question) VALUES ('Would You Rather', 'Be able to teleport anywhere or be able to transform into any animal?');
INSERT INTO wyrs (type, question) VALUES ('Would You Rather', 'Live in a world without music or live in a world without books?');
INSERT INTO wyrs (type, question) VALUES ('Would You Rather', 'Have the ability to control the weather or have the ability to control your dreams?');
INSERT INTO wyrs (type, question) VALUES ('Would You Rather', 'Always have to wear a beret or always have to wear a fedora?');
INSERT INTO wyrs (type, question) VALUES ('Would You Rather', 'Be able to control time or be able to control the minds of others?');
INSERT INTO wyrs (type, question) VALUES ('Would You Rather', 'Live in a world without art or live in a world without science?');
INSERT INTO wyrs (type, question) VALUES ('Would You Rather', 'Have the ability to change your appearance at will or have the ability to change your voice at will?');
INSERT INTO wyrs (type, question) VALUES ('Would You Rather', 'Always have to wear a top hat or always have to wear a bowler hat?');
INSERT INTO wyrs (type, question) VALUES ('Would You Rather', 'Be able to fly like a bird or be able to breathe fire?');
INSERT INTO wyrs (type, question) VALUES ('Would You Rather', 'Live in a world without movies or live in a world without video games?');
INSERT INTO wyrs (type, question) VALUES ('Would You Rather', 'Have the ability to understand and speak all animal languages or have the ability to understand and speak all programming languages?');
INSERT INTO wyrs (type, question) VALUES ('Would You Rather', 'Always have to wear a superhero costume or always have to wear a wizard costume?');
INSERT INTO wyrs (type, question) VALUES ('Would You Rather', 'Be able to control electricity or be able to control magnetism?');
INSERT INTO wyrs (type, question) VALUES ('Would You Rather', 'Live in a world without social media or live in a world without television?');
INSERT INTO wyrs (type, question) VALUES ('Would You Rather', 'Have the ability to read minds or have the ability to see through walls?');
INSERT INTO wyrs (type, question) VALUES ('Would You Rather', 'Live in a world without sports or live in a world without movies?');
INSERT INTO wyrs (type, question) VALUES ('Would You Rather', 'Always have to wear a tiara or always have to wear a bow in your hair?');
INSERT INTO wyrs (type, question) VALUES ('Would You Rather', 'Be able to control the elements (fire, water, earth, air) or be able to shapeshift into any animal?');
INSERT INTO wyrs (type, question) VALUES ('Would You Rather', 'Live in a world without music or live in a world without art?');
INSERT INTO wyrs (type, question) VALUES ('Would You Rather', 'Always have to wear a tuxedo or always have to wear a ball gown?');
INSERT INTO wyrs (type, question) VALUES ('Would You Rather', 'Always have to wear a wizard''s robe or always have to wear a fairy''s dress?');
INSERT INTO wyrs (type, question) VALUES ('Would You Rather', 'Always have to wear a bowtie or always have to wear sunglasses?');
INSERT INTO wyrs (type, question) VALUES ('Would You Rather', 'Be able to fly like a bird or be able to teleport?');
INSERT INTO wyrs (type, question) VALUES ('Would You Rather', 'Live in a world without books or live in a world without movies?');
INSERT INTO wyrs (type, question) VALUES ('Would You Rather', 'Always have to wear a cape or always have to wear a mask?');
INSERT INTO wyrs (type, question) VALUES ('Would You Rather', 'Be able to control fire or control lightning?');
INSERT INTO wyrs (type, question) VALUES ('Would You Rather', 'Have a pet tiger or a pet elephant?');
INSERT INTO wyrs (type, question) VALUES ('Would You Rather', 'Always have to speak in riddles or in song lyrics?');
INSERT INTO wyrs (type, question) VALUES ('Would You Rather', 'Have the ability to freeze time or rewind time?');
INSERT INTO wyrs (type, question) VALUES ('Would You Rather', 'Be a famous actor/actress or a famous musician?');
INSERT INTO wyrs (type, question) VALUES ('Would You Rather', 'Always have to wear a top hat or always have to wear sunglasses?');
INSERT INTO wyrs (type, question) VALUES ('Would You Rather', 'Be able to turn into any animal at will or have the ability to speak and understand all human languages?');
INSERT INTO wyrs (type, question) VALUES ('Would You Rather', 'Be able to communicate with trees or be able to communicate with the ocean?');
INSERT INTO wyrs (type, question) VALUES ('Would You Rather', 'Have a personal makeup artist or a personal trainer?');
INSERT INTO wyrs (type, question) VALUES ('Would You Rather', 'Always have to wear a crown or always have to wear a magic wand?');
INSERT INTO wyrs (type, question) VALUES ('Would You Rather', 'Be able to breathe underwater or have the ability to turn invisible?');
INSERT INTO wyrs (type, question) VALUES ('Would You Rather', 'Live in a castle or live in a spaceship?');
INSERT INTO wyrs (type, question) VALUES ('Would You Rather', 'Have the ability to speak with animals or be able to talk to the dead?');
INSERT INTO wyrs (type, question) VALUES ('Would You Rather', 'Always have to wear a bowtie or a bow in your hair?');
INSERT INTO wyrs (type, question) VALUES ('Would You Rather', 'Live in a world without internet or live in a world without electricity?');
INSERT INTO wyrs (type, question) VALUES ('Would You Rather', 'Have the ability to control fire or have the ability to control time?');
INSERT INTO wyrs (type, question) VALUES ('Would You Rather', 'Be able to teleport anywhere or be able to read minds?');
INSERT INTO wyrs (type, question) VALUES ('Would You Rather', 'Have the ability to control water or have the ability to control electricity?');
INSERT INTO wyrs (type, question) VALUES ('Would You Rather', 'Always have to wear a lab coat or always have to wear a chef''s hat?');
INSERT INTO wyrs (type, question) VALUES ('Would You Rather', 'Have the ability to control the minds of others or have the ability to control the weather?');
INSERT INTO wyrs (type, question) VALUES ('Would You Rather', 'Have bad breath or smelly feet?');
INSERT INTO wyrs (type, question) VALUES ('Would You Rather', 'Fight 1,000 ant-sized bulls or one bull-sized ant?');
INSERT INTO wyrs (type, question) VALUES ('Would You Rather', 'Have a hamster-sized dog or a dog-sized hamster?');
INSERT INTO wyrs (type, question) VALUES ('Would You Rather', 'Have spaghetti for hair or sweat mayonnaise?
');
INSERT INTO wyrs (type, question) VALUES ('Would You Rather', 'Live forever with an eyelash in your eye or spinach in your teeth?');
INSERT INTO wyrs (type, question) VALUES ('Would You Rather', 'Adopt a British accent every time you are having a serious conversation or laugh every time someone cries?');
INSERT INTO wyrs (type, question) VALUES ('Would You Rather', 'Get a face tattoo of something of your choosing or a tattoo in a discreet area chosen by someone else?');
INSERT INTO wyrs (type, question) VALUES ('Would You Rather', 'Talk like Yoda or breathe like Darth Vader?');
INSERT INTO wyrs (type, question) VALUES ('Would You Rather', 'Sneeze every time you say hi or have the urge to pee every time you ask a question?');
INSERT INTO wyrs (type, question) VALUES ('Would You Rather', 'Wear jeans one size too small or shoes two sizes too big?');
INSERT INTO wyrs (type, question) VALUES ('Would You Rather', 'Have a head the size of a tennis ball or the size of a watermelon?');
INSERT INTO wyrs (type, question) VALUES ('Would You Rather', 'Be in a real-life version of The Walking Dead or Jurassic Park?');
INSERT INTO wyrs (type, question) VALUES ('Would You Rather', 'Accidentally like an old photo of your ex on Instagram or accidentally send a naughty text to a relative?');
INSERT INTO wyrs (type, question) VALUES ('Would You Rather', 'Have your Netflix viewing history made public or your Spotify listening history made public?');
INSERT INTO wyrs (type, question) VALUES ('Would You Rather', 'Lose the ability to use GPS for the rest of your life or lose the ability to use a credit card?');
INSERT INTO wyrs (type, question) VALUES ('Would You Rather', 'Only be able to communicate via emojis or only be able to communicate via slang words?');
INSERT INTO wyrs (type, question) VALUES ('Would You Rather', 'Have to hunt for everything you eat or eat only McDonald''s for every meal?');
INSERT INTO wyrs (type, question) VALUES ('Would You Rather', 'Be in a fight club that meets once a month or a book club that meets every day');
INSERT INTO wyrs (type, question) VALUES ('Would You Rather', 'Always say what you are thinking or never be able to speak again?');
INSERT INTO wyrs (type, question) VALUES ('Would You Rather', 'Be forced to sing along to every song that you hear or be forced to dance along to every song that you hear?');
INSERT INTO wyrs (type, question) VALUES ('Would You Rather', 'Live in the Harry Potter universe with no powers or be a Death Eater?');
INSERT INTO wyrs (type, question) VALUES ('Would You Rather', 'Go without deodorant the day you meet your celebrity crush or run into them when you just rolled out of bed?');
INSERT INTO wyrs (type, question) VALUES ('Would You Rather', 'Have "Baby Shark" stuck in your head forever or the jingle from your least favorite commercial');
INSERT INTO wyrs (type, question) VALUES ('Would You Rather', 'Your pet be able to speak to you but not understand what you are saying or your pet understand every word you say but not be able to speak');
INSERT INTO wyrs (type, question) VALUES ('Would You Rather', 'Watch your most embarrassing childhood moment on a one-hour loop every month or remember it once every day for the rest of your life?');
INSERT INTO wyrs (type, question) VALUES ('Would You Rather', 'Sing your favorite song all by yourself in front of an arena full of people or just in front of the original artist alone?');
INSERT INTO wyrs (type, question) VALUES ('Would You Rather', 'Glow bright pink every time you are attracted to someone or glow bright red every time someone annoys you?');
INSERT INTO wyrs (type, question) VALUES ('Would You Rather', 'Give away all your money or all your possessions?');
INSERT INTO wyrs (type, question) VALUES ('Would You Rather', 'Let your boss or your parents see your full internet history?');
INSERT INTO wyrs (type, question) VALUES ('Would You Rather', 'Wear hideous glasses that are perfect for your eyesight or flattering ones that make your vision a tiny bit blurry?');
INSERT INTO wyrs (type, question) VALUES ('Would You Rather', 'Own a car with a horn that plays "YMCA" every time you touch it or own a car with your kid''s favorite cartoon painted on the side?');
INSERT INTO wyrs (type, question) VALUES ('Would You Rather', 'Have to wear a bib every time you go out to eat or drink from a sippy cup every time you are at a bar?');
INSERT INTO wyrs (type, question) VALUES ('Would You Rather', 'Walk through Disneyland wearing a shirt with your most embarrassing childhood nickname on it or go to your class reunion with a big zit?');
INSERT INTO wyrs (type, question) VALUES ('Would You Rather', 'Speak only in a baby voice for a day or only be spoken to in a baby voice for a day?');
INSERT INTO wyrs (type, question) VALUES ('Would You Rather', 'Be captured by pirates or Old West bad guys?');
INSERT INTO wyrs (type, question) VALUES ('Would You Rather', 'Wear sweatpants every day for the rest of your life or never wear sweatpants again?');
INSERT INTO wyrs (type, question) VALUES ('Would You Rather', 'Burp soap bubbles when you are drunk or have your hair turn green when you are drunk?');
INSERT INTO wyrs (type, question) VALUES ('Would You Rather', 'Have a driver to take you everywhere or a private chef who makes all your meals?');
INSERT INTO wyrs (type, question) VALUES ('Would You Rather', 'Have to keep a terrible haircut for a month or let your mother dress you for a month?');
INSERT INTO wyrs (type, question) VALUES ('Would You Rather', 'Take unlimited plane trips in a middle seat or one a year in the most extravagant first-class cabin?');
INSERT INTO wyrs (type, question) VALUES ('Would You Rather', 'Inherit $20 million or earn $50 million through hard work and dedication');
INSERT INTO wyrs (type, question) VALUES ('Would You Rather', 'Sell all your possessions and hit the road in an R.V. or have everything you want at your fingertips and never be able to travel?');
INSERT INTO wyrs (type, question) VALUES ('Would You Rather', 'Have a backstage pass to see your favorite artist or a ticket to a premiere with your favorite actor?');
INSERT INTO wyrs (type, question) VALUES ('Would You Rather', 'Make decent money doing what you love or get rich from a job that you hate?');
INSERT INTO wyrs (type, question) VALUES ('Would You Rather', 'The aliens that first make contact be robotic or organic?');
INSERT INTO wyrs (type, question) VALUES ('Would You Rather', 'Be able to see 10 years into your own future or six months into the future of the world?');
INSERT INTO wyrs (type, question) VALUES ('Would You Rather', 'Have psychic powers or the ability to remember every fact you learn?');
INSERT INTO wyrs (type, question) VALUES ('Would You Rather', 'Have the power of invisibility or be able to fly?');
INSERT INTO wyrs (type, question) VALUES ('Would You Rather', 'Have to kiss every person you meet or never kiss your partner again?');
INSERT INTO wyrs (type, question) VALUES ('Would You Rather', 'Have to shower every day in scalding hot water or in freezing cold water?');
INSERT INTO wyrs (type, question) VALUES ('Would You Rather', 'Know when you are going to die or how you are going to die?');
INSERT INTO wyrs (type, question) VALUES ('Would You Rather', 'Lose the ability to read or the ability to speak?');
INSERT INTO wyrs (type, question) VALUES ('Would You Rather', 'Never have to wait in line or always have a parking spot?');
INSERT INTO wyrs (type, question) VALUES ('Would You Rather', 'Never be able to die or have to relive your death over and over for all of eternity?');
INSERT INTO wyrs (type, question) VALUES ('Would You Rather', 'Sing everything you say or dance every time you walk?');
INSERT INTO wyrs (type, question) VALUES ('Would You Rather', 'Lose a finger or have a headache every day for the rest of your life?');
INSERT INTO wyrs (type, question) VALUES ('Would You Rather', 'Always get stuck in traffic or always have a terribly slow internet connection?');
INSERT INTO wyrs (type, question) VALUES ('Would You Rather', 'Never use the internet again or never fly on an airplane again?');
INSERT INTO wyrs (type, question) VALUES ('Dirty Would You Rather', 'Cuddle up in front of a fireplace, or light your fire in bed?');
INSERT INTO wyrs (type, question) VALUES ('Dirty Would You Rather', 'Wrestle naked in a pool of Jell-O or chocolate pudding?');
INSERT INTO wyrs (type, question) VALUES ('Dirty Would You Rather', 'Make whoopee in your parents'' bed or at a mattress store?');
INSERT INTO wyrs (type, question) VALUES ('Dirty Would You Rather', 'Accidentally send a dirty text to your boss or a sexy voicemail to your mom?');
INSERT INTO wyrs (type, question) VALUES ('Dirty Would You Rather', 'Lose your sense of feeling during love or lose your sense of taste?');
INSERT INTO wyrs (type, question) VALUES ('Dirty Would You Rather', 'Play teacher''s pet or play doctor?');
INSERT INTO wyrs (type, question) VALUES ('Dirty Would You Rather', 'Have your man dress as a manly lumberjack or a sharp-dressed man?');
INSERT INTO wyrs (type, question) VALUES ('Dirty Would You Rather', 'Walk in on your parents making love, or have them walk in on you?');
INSERT INTO wyrs (type, question) VALUES ('Dirty Would You Rather', 'Be caught in the act by a cop or your in-laws?');
INSERT INTO wyrs (type, question) VALUES ('Dirty Would You Rather', 'Be on top or on the bottom?');

-- Never Have I Have
INSERT INTO nhies (type, question) VALUES ('Never Have I Ever', 'Eaten a whole cake by myself');
INSERT INTO nhies (type, question) VALUES ('Never Have I Ever', 'Gone skydiving');
INSERT INTO nhies (type, question) VALUES ('Never Have I Ever', 'Traveled to another continent');
INSERT INTO nhies (type, question) VALUES ('Never Have I Ever', 'Sung karaoke in front of a crowd');
INSERT INTO nhies (type, question) VALUES ('Never Have I Ever', 'Dyed my hair a vibrant color');
INSERT INTO nhies (type, question) VALUES ('Never Have I Ever', 'Broken a bone');
INSERT INTO nhies (type, question) VALUES ('Never Have I Ever', 'Bungee jumped');
INSERT INTO nhies (type, question) VALUES ('Never Have I Ever', 'Gone vegan or vegetarian');
INSERT INTO nhies (type, question) VALUES ('Never Have I Ever', 'Tried surfing');
INSERT INTO nhies (type, question) VALUES ('Never Have I Ever', 'Learned to play a musical instrument');
INSERT INTO nhies (type, question) VALUES ('Never Have I Ever', 'Gone snowboarding or skiing');
INSERT INTO nhies (type, question) VALUES ('Never Have I Ever', 'Gotten a tattoo');
INSERT INTO nhies (type, question) VALUES ('Never Have I Ever', 'Climbed a mountain');
INSERT INTO nhies (type, question) VALUES ('Never Have I Ever', 'Learned to speak a foreign language fluently');
INSERT INTO nhies (type, question) VALUES ('Never Have I Ever', 'Gone parasailing');
INSERT INTO nhies (type, question) VALUES ('Never Have I Ever', 'Performed on stage in front of an audience');
INSERT INTO nhies (type, question) VALUES ('Never Have I Ever', 'Been in a helicopter');
INSERT INTO nhies (type, question) VALUES ('Never Have I Ever', 'Done a marathon or long-distance race');
INSERT INTO nhies (type, question) VALUES ('Never Have I Ever', 'Visited a famous landmark (e.g., Eiffel Tower, Great Wall of China)');
INSERT INTO nhies (type, question) VALUES ('Never Have I Ever', 'Gone zip-lining');
INSERT INTO nhies (type, question) VALUES ('Never Have I Ever', 'Learned to ride a bicycle');
INSERT INTO nhies (type, question) VALUES ('Never Have I Ever', 'Gone skinny-dipping');
INSERT INTO nhies (type, question) VALUES ('Never Have I Ever', 'Met a celebrity in person');
INSERT INTO nhies (type, question) VALUES ('Never Have I Ever', 'Ridden a horse');
INSERT INTO nhies (type, question) VALUES ('Never Have I Ever', 'Gone camping');
INSERT INTO nhies (type, question) VALUES ('Never Have I Ever', 'Gone on a road trip across multiple countries');
INSERT INTO nhies (type, question) VALUES ('Never Have I Ever', 'Ridden a roller coaster');
INSERT INTO nhies (type, question) VALUES ('Never Have I Ever', 'Gone on a spontaneous trip without planning');
INSERT INTO nhies (type, question) VALUES ('Never Have I Ever', 'Learned to dance a specific style (e.g., salsa, ballet)');
INSERT INTO nhies (type, question) VALUES ('Never Have I Ever', 'Tried a spicy food challenge');
INSERT INTO nhies (type, question) VALUES ('Never Have I Ever', 'Visited a famous national park');
INSERT INTO nhies (type, question) VALUES ('Never Have I Ever', 'Tried stand-up paddleboarding');
INSERT INTO nhies (type, question) VALUES ('Never Have I Ever', 'Been on a hot air balloon ride');
INSERT INTO nhies (type, question) VALUES ('Never Have I Ever', 'Taken a spontaneous road trip');
INSERT INTO nhies (type, question) VALUES ('Never Have I Ever', 'Tried scuba diving');
INSERT INTO nhies (type, question) VALUES ('Never Have I Ever', 'Gone on a backpacking trip');
INSERT INTO nhies (type, question) VALUES ('Never Have I Ever', 'Tried deep-sea fishing');
INSERT INTO nhies (type, question) VALUES ('Never Have I Ever', 'Visited a famous cathedral');
INSERT INTO nhies (type, question) VALUES ('Never Have I Ever', 'Been on a road trip');
INSERT INTO nhies (type, question) VALUES ('Never Have I Ever', 'Visited a famous art gallery');
INSERT INTO nhies (type, question) VALUES ('Never Have I Ever', 'Tried water skiing');
INSERT INTO nhies (type, question) VALUES ('Never Have I Ever', 'Visited a famous beach');
INSERT INTO nhies (type, question) VALUES ('Never Have I Ever', 'Tried snowshoeing');
INSERT INTO nhies (type, question) VALUES ('Never Have I Ever', 'Gone on a safari');
INSERT INTO nhies (type, question) VALUES ('Never Have I Ever', 'Visited a famous waterfall');
INSERT INTO nhies (type, question) VALUES ('Never Have I Ever', 'Participated in a dance competition');
INSERT INTO nhies (type, question) VALUES ('Never Have I Ever', 'Tried kayaking');
INSERT INTO nhies (type, question) VALUES ('Never Have I Ever', 'Gone on a ghost tour');
INSERT INTO nhies (type, question) VALUES ('Never Have I Ever', 'Visited a famous castle');
INSERT INTO nhies (type, question) VALUES ('Never Have I Ever', 'Tried mountain biking');
INSERT INTO nhies (type, question) VALUES ('Never Have I Ever', 'Been on a solo trip');
INSERT INTO nhies (type, question) VALUES ('Never Have I Ever', 'Visited a famous city');
INSERT INTO nhies (type, question) VALUES ('Never Have I Ever', 'Tried cross-country skiing');
INSERT INTO nhies (type, question) VALUES ('Never Have I Ever', 'Gone on a gondola ride');
INSERT INTO nhies (type, question) VALUES ('Never Have I Ever', 'Visited a famous volcano');
INSERT INTO nhies (type, question) VALUES ('Never Have I Ever', 'Tried paddleboarding');
INSERT INTO nhies (type, question) VALUES ('Never Have I Ever', 'Participated in a stand-up comedy show');
INSERT INTO nhies (type, question) VALUES ('Never Have I Ever', 'Tried kiteboarding');
INSERT INTO nhies (type, question) VALUES ('Never Have I Ever', 'Tried indoor rock climbing');
INSERT INTO nhies (type, question) VALUES ('Never Have I Ever', 'Gone on a horseback riding tour');
INSERT INTO nhies (type, question) VALUES ('Never Have I Ever', 'Visited a famous archaeological site');
INSERT INTO nhies (type, question) VALUES ('Never Have I Ever', 'Tried wakeboarding');
INSERT INTO nhies (type, question) VALUES ('Never Have I Ever', 'Participated in a pub crawl');
INSERT INTO nhies (type, question) VALUES ('Never Have I Ever', 'Gone on a wine tour');
INSERT INTO nhies (type, question) VALUES ('Never Have I Ever', 'Visited a famous temple');
INSERT INTO nhies (type, question) VALUES ('Never Have I Ever', 'Ridden a motorcycle');
INSERT INTO nhies (type, question) VALUES ('Never Have I Ever', 'Been on a cruise');
INSERT INTO nhies (type, question) VALUES ('Never Have I Ever', 'Eaten escargot (snails)');
INSERT INTO nhies (type, question) VALUES ('Never Have I Ever', 'Gone ice skating');
INSERT INTO nhies (type, question) VALUES ('Never Have I Ever', 'Been to a music festival');
INSERT INTO nhies (type, question) VALUES ('Never Have I Ever', 'Gone on a blind date');
INSERT INTO nhies (type, question) VALUES ('Never Have I Ever', 'Been on live television');
INSERT INTO nhies (type, question) VALUES ('Never Have I Ever', 'Had a pet other than a cat or dog');
INSERT INTO nhies (type, question) VALUES ('Never Have I Ever', 'Gone snorkeling');
INSERT INTO nhies (type, question) VALUES ('Never Have I Ever', 'Learned to swim');
INSERT INTO nhies (type, question) VALUES ('Never Have I Ever', 'Tried sushi');
INSERT INTO nhies (type, question) VALUES ('Never Have I Ever', 'Gone on a date with someone I met online');
INSERT INTO nhies (type, question) VALUES ('Never Have I Ever', 'Visited a famous museum');
INSERT INTO nhies (type, question) VALUES ('Never Have I Ever', 'Been on a helicopter tour');
INSERT INTO nhies (type, question) VALUES ('Never Have I Ever', 'Participated in a cooking class');
INSERT INTO nhies (type, question) VALUES ('Never Have I Ever', 'Written a fantasy novel');
INSERT INTO nhies (type, question) VALUES ('Never Have I Ever', 'Created a viral video');
INSERT INTO nhies (type, question) VALUES ('Never Have I Ever', 'Designed a mobile app');
INSERT INTO nhies (type, question) VALUES ('Never Have I Ever', 'Produced a short film');
INSERT INTO nhies (type, question) VALUES ('Never Have I Ever', 'Developed a board game');
INSERT INTO nhies (type, question) VALUES ('Never Have I Ever', 'Painted a mural');
INSERT INTO nhies (type, question) VALUES ('Never Have I Ever', 'Composed a song');
INSERT INTO nhies (type, question) VALUES ('Never Have I Ever', 'Built a website from scratch');
INSERT INTO nhies (type, question) VALUES ('Never Have I Ever', 'Created a podcast series');
INSERT INTO nhies (type, question) VALUES ('Never Have I Ever', 'Directed a theater play');
INSERT INTO nhies (type, question) VALUES ('Never Have I Ever', 'Designed a fashion collection');
INSERT INTO nhies (type, question) VALUES ('Dirty Never Have I Ever', 'Had a one-night stand');
INSERT INTO nhies (type, question) VALUES ('Dirty Never Have I Ever', 'Sent a nude photo');
INSERT INTO nhies (type, question) VALUES ('Dirty Never Have I Ever', 'Engaged in a threesome');
INSERT INTO nhies (type, question) VALUES ('Dirty Never Have I Ever', 'Used a sex toy');
INSERT INTO nhies (type, question) VALUES ('Dirty Never Have I Ever', 'Had a friends-with-benefits arrangement');
INSERT INTO nhies (type, question) VALUES ('Dirty Never Have I Ever', 'Engaged in bondage or BDSM');
INSERT INTO nhies (type, question) VALUES ('Dirty Never Have I Ever', 'Had a one-night stand with a stranger');
INSERT INTO nhies (type, question) VALUES ('Dirty Never Have I Ever', 'Watched pornography');
INSERT INTO nhies (type, question) VALUES ('Dirty Never Have I Ever', 'Had phone or cybersex');
INSERT INTO nhies (type, question) VALUES ('Dirty Never Have I Ever', 'Role-played during intimate activities');
INSERT INTO nhies (type, question) VALUES ('Dirty Never Have I Ever', 'Engaged in public sexual activities');
INSERT INTO nhies (type, question) VALUES ('Dirty Never Have I Ever', 'Used handcuffs or restraints during intimate activities');
INSERT INTO nhies (type, question) VALUES ('Dirty Never Have I Ever', 'Had sex in a car');
INSERT INTO nhies (type, question) VALUES ('Dirty Never Have I Ever', 'Engaged in voyeurism or exhibitionism');
INSERT INTO nhies (type, question) VALUES ('Dirty Never Have I Ever', 'Had sex in a public place');
INSERT INTO nhies (type, question) VALUES ('Dirty Never Have I Ever', 'Engaged in anal sex');
INSERT INTO nhies (type, question) VALUES ('Dirty Never Have I Ever', 'Used edible body paint or lingerie');
INSERT INTO nhies (type, question) VALUES ('Dirty Never Have I Ever', 'Had a sexual fantasy about someone I know');
INSERT INTO nhies (type, question) VALUES ('Dirty Never Have I Ever', 'Engaged in sexting');
INSERT INTO nhies (type, question) VALUES ('Dirty Never Have I Ever', 'Had a threesome with two people of the same sex');
INSERT INTO nhies (type, question) VALUES ('Dirty Never Have I Ever', 'Had a one-night stand while in a committed relationship');
INSERT INTO nhies (type, question) VALUES ('Dirty Never Have I Ever', 'Engaged in role reversal or power play during intimate activities');
INSERT INTO nhies (type, question) VALUES ('Dirty Never Have I Ever', 'Used a blindfold during intimate activities');
INSERT INTO nhies (type, question) VALUES ('Dirty Never Have I Ever', 'Had sex in a public restroom');
INSERT INTO nhies (type, question) VALUES ('Dirty Never Have I Ever', 'Engaged in sexual activities with multiple partners in one day');
INSERT INTO nhies (type, question) VALUES ('Dirty Never Have I Ever', 'Used a sex swing or other sex furniture');
INSERT INTO nhies (type, question) VALUES ('Dirty Never Have I Ever', 'Had a sexual encounter with a celebrity');
INSERT INTO nhies (type, question) VALUES ('Dirty Never Have I Ever', 'Engaged in sexual role-playing with costumes');
INSERT INTO nhies (type, question) VALUES ('Dirty Never Have I Ever', 'Used a safe word during intimate activities');
INSERT INTO nhies (type, question) VALUES ('Never Have I Ever', 'Watched a horror movie alone at night');
INSERT INTO nhies (type, question) VALUES ('Never Have I Ever', 'Visited a haunted house');
INSERT INTO nhies (type, question) VALUES ('Never Have I Ever', 'Slept in a room that is rumored to be haunted');
INSERT INTO nhies (type, question) VALUES ('Never Have I Ever', 'Read a scary book and could nott sleep afterwards');
INSERT INTO nhies (type, question) VALUES ('Never Have I Ever', 'Tried to summon a ghost or spirit');
INSERT INTO nhies (type, question) VALUES ('Never Have I Ever', 'Participated in a paranormal investigation');
INSERT INTO nhies (type, question) VALUES ('Never Have I Ever', 'Been to a horror-themed amusement park');
INSERT INTO nhies (type, question) VALUES ('Never Have I Ever', 'Tried to watch a horror movie, but had to turn it off because it was too scary');
INSERT INTO nhies (type, question) VALUES ('Never Have I Ever', 'Had a nightmare that kept me awake');
INSERT INTO nhies (type, question) VALUES ('Never Have I Ever', 'Visited a real-life haunted location');
INSERT INTO nhies (type, question) VALUES ('Never Have I Ever', 'Dressed up as a horror movie character for Halloween');
INSERT INTO nhies (type, question) VALUES ('Never Have I Ever', 'Been startled by a jump scare in a horror movie');
INSERT INTO nhies (type, question) VALUES ('Never Have I Ever', 'Watched a horror movie marathon');
INSERT INTO nhies (type, question) VALUES ('Never Have I Ever', 'Explored an abandoned building at night');
INSERT INTO nhies (type, question) VALUES ('Never Have I Ever', 'Told scary stories around a campfire');
INSERT INTO nhies (type, question) VALUES ('Never Have I Ever', 'Attended a midnight screening of a horror movie');
INSERT INTO nhies (type, question) VALUES ('Never Have I Ever', 'Believed in ghosts or supernatural beings');
INSERT INTO nhies (type, question) VALUES ('Never Have I Ever', 'Visited a cemetery after dark');
INSERT INTO nhies (type, question) VALUES ('Never Have I Ever', 'Had a paranormal experience');
INSERT INTO nhies (type, question) VALUES ('Never Have I Ever', 'Explored an underwater cave');
INSERT INTO nhies (type, question) VALUES ('Never Have I Ever', 'Participated in a professional video game tournament');
INSERT INTO nhies (type, question) VALUES ('Never Have I Ever', 'Learned to speak a fictional language (e.g., Elvish, Klingon)');
INSERT INTO nhies (type, question) VALUES ('Never Have I Ever', 'Built a treehouse');
INSERT INTO nhies (type, question) VALUES ('Never Have I Ever', 'Performed a stand-up comedy routine');
INSERT INTO nhies (type, question) VALUES ('Never Have I Ever', 'Participated in a reality TV show');
INSERT INTO nhies (type, question) VALUES ('Never Have I Ever', 'Explored a deep cave system');
INSERT INTO nhies (type, question) VALUES ('Never Have I Ever', 'Solved a Rubik''s Cube');
INSERT INTO nhies (type, question) VALUES ('Never Have I Ever', 'Gone on a multi-day silent retreat');
INSERT INTO nhies (type, question) VALUES ('Never Have I Ever', 'Spent a night stargazing in the desert');
INSERT INTO nhies (type, question) VALUES ('Never Have I Ever', 'Reached the top rank in an online multiplayer game');
INSERT INTO nhies (type, question) VALUES ('Never Have I Ever', 'Participated in a video game tournament');


-- paranoias
INSERT INTO paranoias (type, question) VALUES ('Paranoia', 'What if everyone is secretly watching and judging me?');
INSERT INTO paranoias (type, question) VALUES ('Paranoia', 'What if someone is reading my thoughts?');
INSERT INTO paranoias (type, question) VALUES ('Paranoia', 'What if my phone is listening to my conversations?');
INSERT INTO paranoias (type, question) VALUES ('Paranoia', 'What if I am being followed without knowing it?');
INSERT INTO paranoias (type, question) VALUES ('Paranoia', 'What if my computer is hacked and someone is monitoring my activities?');
INSERT INTO paranoias (type, question) VALUES ('Paranoia', 'What if there are hidden cameras in my home?');
INSERT INTO paranoias (type, question) VALUES ('Paranoia', 'What if I accidentally reveal a secret without realizing it?');
INSERT INTO paranoias (type, question) VALUES ('Paranoia', 'What if someone is impersonating me online?');
INSERT INTO paranoias (type, question) VALUES ('Paranoia', 'What if there are hidden microphones in public places?');
INSERT INTO paranoias (type, question) VALUES ('Paranoia', 'What if my social media accounts are being monitored?');
INSERT INTO paranoias (type, question) VALUES ('Paranoia', 'What if my food or drinks are being tampered with?');
INSERT INTO paranoias (type, question) VALUES ('Paranoia', 'What if my friends are secretly talking behind my back?');
INSERT INTO paranoias (type, question) VALUES ('Paranoia', 'What if I accidentally reveal sensitive information to the wrong person?');
INSERT INTO paranoias (type, question) VALUES ('Paranoia', 'What if my online accounts are hacked and my personal information is stolen?');
INSERT INTO paranoias (type, question) VALUES ('Paranoia', 'What if someone is following me on social media without my knowledge?');
INSERT INTO paranoias (type, question) VALUES ('Paranoia', 'What if there are hidden trackers on my car?');
INSERT INTO paranoias (type, question) VALUES ('Paranoia', 'What if I am being watched through my webcam?');
INSERT INTO paranoias (type, question) VALUES ('Paranoia', 'What if my emails are being intercepted and read by someone else?');
INSERT INTO paranoias (type, question) VALUES ('Paranoia', 'What if I am being recorded without my consent?');
INSERT INTO paranoias (type, question) VALUES ('Paranoia', 'What if there are hidden listening devices in my home?');
INSERT INTO paranoias (type, question) VALUES ('Paranoia', 'What if my personal information is being sold on the dark web?');
INSERT INTO paranoias (type, question) VALUES ('Paranoia', 'What if my neighbors are spying on me?');
INSERT INTO paranoias (type, question) VALUES ('Paranoia', 'What if my online activities are being tracked and monitored?');
INSERT INTO paranoias (type, question) VALUES ('Paranoia', 'What if I am being watched through public surveillance cameras?');
INSERT INTO paranoias (type, question) VALUES ('Paranoia', 'What if my private conversations are being recorded?');
INSERT INTO paranoias (type, question) VALUES ('Paranoia', 'What if my identity is stolen and used for illegal activities?');
INSERT INTO paranoias (type, question) VALUES ('Paranoia', 'What if there are hidden bugs in my home?');
INSERT INTO paranoias (type, question) VALUES ('Paranoia', 'What if my credit card information is stolen during online transactions?');
INSERT INTO paranoias (type, question) VALUES ('Paranoia', 'What if someone is tampering with my mail?');
INSERT INTO paranoias (type, question) VALUES ('Paranoia', 'What if my online posts and comments are used against me in the future?');
INSERT INTO paranoias (type, question) VALUES ('Paranoia', 'What if my personal photos and videos are leaked online?');
INSERT INTO paranoias (type, question) VALUES ('Paranoia', 'What if my devices are infected with malware or viruses?');
INSERT INTO paranoias (type, question) VALUES ('Paranoia', 'What if my personal documents and files are accessed without my knowledge?');
INSERT INTO paranoias (type, question) VALUES ('Paranoia', 'What if my passwords are compromised and someone gains unauthorized access to my accounts?');
INSERT INTO paranoias (type, question) VALUES ('Paranoia', 'What if my conversations are being eavesdropped on in public places?');
INSERT INTO paranoias (type, question) VALUES ('Paranoia', 'What if my location is being tracked without my consent?');
INSERT INTO paranoias (type, question) VALUES ('Paranoia', 'What if my online search history is being monitored?');
INSERT INTO paranoias (type, question) VALUES ('Paranoia', 'What if my social media posts are used against me in real life?');
INSERT INTO paranoias (type, question) VALUES ('Paranoia', 'What if my online purchases are being tracked for targeted advertising?');
INSERT INTO paranoias (type, question) VALUES ('Paranoia', 'What if my personal data is sold to third parties without my permission?');
INSERT INTO paranoias (type, question) VALUES ('Paranoia', 'What if my conversations are being recorded by smart devices in my home?');
INSERT INTO paranoias (type, question) VALUES ('Paranoia', 'What if my personal information is leaked due to a data breach?');
INSERT INTO paranoias (type, question) VALUES ('Paranoia', 'What if my online profiles are being impersonated by someone else?');
INSERT INTO paranoias (type, question) VALUES ('Paranoia', 'What if my phone calls are being monitored by unknown entities?');
INSERT INTO paranoias (type, question) VALUES ('Paranoia', 'What if there are hidden cameras in public restrooms?');
INSERT INTO paranoias (type, question) VALUES ('Paranoia', 'What if my online activities are being used for targeted surveillance?');
INSERT INTO paranoias (type, question) VALUES ('Paranoia', 'What if my personal conversations are being monitored by voice assistants?');
INSERT INTO paranoias (type, question) VALUES ('Paranoia', 'What if my computer webcam is hacked and someone is watching me?');
INSERT INTO paranoias (type, question) VALUES ('Paranoia', 'What if my online accounts are vulnerable to hacking and unauthorized access?');
INSERT INTO paranoias (type, question) VALUES ('Paranoia', 'What if my personal photos and videos are accidentally shared with the wrong person?');
INSERT INTO paranoias (type, question) VALUES ('Paranoia', 'What if someone is secretly streaming my Twitch broadcasts without my knowledge?');
INSERT INTO paranoias (type, question) VALUES ('Paranoia', 'What if my chat interactions are being monitored by malicious actors?');
INSERT INTO paranoias (type, question) VALUES ('Paranoia', 'What if my viewers are secretly gathering personal information about me?');
INSERT INTO paranoias (type, question) VALUES ('Paranoia', 'What if my Twitch emotes are being used inappropriately by others?');
INSERT INTO paranoias (type, question) VALUES ('Paranoia', 'What if my Twitch channel is being targeted by trolls or harassers?');
INSERT INTO paranoias (type, question) VALUES ('Paranoia', 'What if my Twitch account gets suspended or banned for unknown reasons?');
INSERT INTO paranoias (type, question) VALUES ('Paranoia', 'What if my Twitch chat is infiltrated by bots or fake accounts?');
INSERT INTO paranoias (type, question) VALUES ('Paranoia', 'What if my Twitch VODs or clips are being used without my permission?');
INSERT INTO paranoias (type, question) VALUES ('Paranoia', 'What if my Twitch stream is being manipulated to show false viewer counts?');
INSERT INTO paranoias (type, question) VALUES ('Paranoia', 'What if my Twitch stream is being sabotaged by competitors?');
INSERT INTO paranoias (type, question) VALUES ('Paranoia', 'What if my Twitch channel''s donation system is compromised?');
INSERT INTO paranoias (type, question) VALUES ('Paranoia', 'What if my Twitch stream is being recorded and distributed without my consent?');
INSERT INTO paranoias (type, question) VALUES ('Paranoia', 'What if my Twitch channel is being targeted for false copyright claims?');
INSERT INTO paranoias (type, question) VALUES ('Paranoia', 'What if my Twitch subscribers are secretly sharing my exclusive content?');
INSERT INTO paranoias (type, question) VALUES ('Paranoia', 'What if my Twitch stream is being targeted by doxxing attempts?');
INSERT INTO paranoias (type, question) VALUES ('Paranoia', 'What if my Twitch channel is being subjected to malicious raids?');
INSERT INTO paranoias (type, question) VALUES ('Paranoia', 'What if my Twitch stream is being used to spread misinformation or propaganda?');
INSERT INTO paranoias (type, question) VALUES ('Paranoia', 'What if my Twitch channel''s chat logs are leaked to the public?');
INSERT INTO paranoias (type, question) VALUES ('Paranoia', 'What if my Twitch account is hacked and my stream key is stolen?');
INSERT INTO paranoias (type, question) VALUES ('Paranoia', 'What if my Twitch stream is being shadowbanned or hidden from viewers?');
INSERT INTO paranoias (type, question) VALUES ('Paranoia', 'What if my Twitch channel''s moderation tools are compromised?');
INSERT INTO paranoias (type, question) VALUES ('Paranoia', 'What if my Twitch stream is being monitored by unauthorized individuals?');
INSERT INTO paranoias (type, question) VALUES ('Paranoia', 'What if my Twitch channel is subjected to false accusations or rumors?');
INSERT INTO paranoias (type, question) VALUES ('Paranoia', 'What if my Twitch stream is being targeted by DDoS attacks?');
INSERT INTO paranoias (type, question) VALUES ('Paranoia', 'What if my Twitch chat messages are being manipulated or altered?');
INSERT INTO paranoias (type, question) VALUES ('Paranoia', 'What if my Twitch channel''s content is stolen and re-uploaded on other platforms?');
INSERT INTO paranoias (type, question) VALUES ('Paranoia', 'What if my Twitch stream is being subjected to viewbotting or followbotting?');
INSERT INTO paranoias (type, question) VALUES ('Paranoia', 'What if my Twitch channel''s revenue is being manipulated or stolen?');
INSERT INTO paranoias (type, question) VALUES ('Paranoia', 'What if my Twitch stream is being secretly restreamed on other platforms?');
INSERT INTO paranoias (type, question) VALUES ('Paranoia', 'What if my Twitch channel''s subscriber information is accessed without authorization?');
INSERT INTO paranoias (type, question) VALUES ('Paranoia', 'What if my Twitch stream is being monitored by unauthorized companies for targeted ads?');
INSERT INTO paranoias (type, question) VALUES ('Paranoia', 'What if my Twitch channel''s chat is being monitored for politically sensitive discussions?');
INSERT INTO paranoias (type, question) VALUES ('Paranoia', 'What if my Twitch stream is being manipulated to display false chat messages?');
INSERT INTO paranoias (type, question) VALUES ('Paranoia', 'What if my Twitch channel''s partnership or affiliate status is revoked without reason?');
INSERT INTO paranoias (type, question) VALUES ('Paranoia', 'What if my Twitch stream is being used to spread malware or phishing attempts?');
INSERT INTO paranoias (type, question) VALUES ('Paranoia', 'What if my Twitch channel''s chat is infiltrated by hate speech or offensive content?');
INSERT INTO paranoias (type, question) VALUES ('Paranoia', 'What if my Twitch stream is being subjected to unauthorized stream interruptions or pauses?');
INSERT INTO paranoias (type, question) VALUES ('Paranoia', 'What if my Twitch channel''s emotes or graphics are plagiarized by others?');
INSERT INTO paranoias (type, question) VALUES ('Paranoia', 'What if my Twitch stream is being used to promote illegal activities?');
INSERT INTO paranoias (type, question) VALUES ('Paranoia', 'What if my Twitch channel''s stream delay is manipulated to gain an unfair advantage?');
INSERT INTO paranoias (type, question) VALUES ('Paranoia', 'What if my Twitch stream is being subjected to false DMCA takedown requests?');
INSERT INTO paranoias (type, question) VALUES ('Paranoia', 'What if my Twitch channel''s stream quality is intentionally lowered by external forces?');
INSERT INTO paranoias (type, question) VALUES ('Paranoia', 'What if my Twitch stream is being monitored for potential terms of service violations?');
INSERT INTO paranoias (type, question) VALUES ('Paranoia', 'What if my Twitch channel''s content is being censored or restricted by unknown entities?');
INSERT INTO paranoias (type, question) VALUES ('Paranoia', 'What if my Twitch stream is being targeted by hate raids or harassment campaigns?');
INSERT INTO paranoias (type, question) VALUES ('Paranoia', 'What if my Twitch channel''s follower count is artificially inflated or deflated?');
INSERT INTO paranoias (type, question) VALUES ('Paranoia', 'What if my Twitch stream is being used to distribute illegal or pirated content?');
INSERT INTO paranoias (type, question) VALUES ('Paranoia', 'What if my Twitch channel''s chat moderation actions are being manipulated by trolls?');
INSERT INTO paranoias (type, question) VALUES ('Paranoia', 'What if my Twitch stream is being monitored for potential privacy breaches?');
INSERT INTO paranoias (type, question) VALUES ('Paranoia', 'What if my Twitch channel''s subscriber notifications are intercepted or blocked?');

SELECT * FROM truths;

-- psql twitch-app -f migration.sql 